app_main/application/urls.py
from django.contrib import admin
from django.urls import include, path

from application import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace="main")),
    path('catalog/', include('products.urls', namespace="catalog")),
    path('user/', include('users.urls', namespace="user")),
    path('basket/', include('baskets.urls', namespace="basket")),
]

if settings.DEBUG:
    urlpatterns += [path("__debug__/", include("debug_toolbar.urls")),]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_main/main/urls.py
from django.urls import path
from main import views

app_name = "main"

urlpatterns = [
    path('', view=views.index, name='index'),
    path('about/', view=views.about, name='about'),
]

app_main/products/urls.py
from django.urls import path
from products import views

app_name = "products"

urlpatterns = [
    path('search/', view=views.catalog, name='search'),
    path('<slug:category_slug>', view=views.catalog, name='index'),
    path('product/<slug:product_slug>/', view=views.product, name='product'),
]

app_main/users/urls.py
from django.urls import path
from users import views

app_name = "users"

urlpatterns = [
    path('login/', view=views.login, name='login'),
    path('registration/', view=views.registration, name='registration'),
    path('profile/', view=views.profile, name='profile'),
    path('logout/', view=views.logout, name='logout'),
    path('users-basket/', view=views.users_basket, name='users_basket'),
]

app_main/main/views.py
from django.shortcuts import render


def index(request):
    context = {
        "title": "Home - Главная",
        "content": "Pizza House HOME",
    }
    return render(request=request, template_name='main/index.html', context=context)


def about(request):
    context = {
        "title": "About - Про нас",
        "content": "About Page",
        "text_on_page": f"Мы — команда профессионалов, которая с любовью и страстью создает самую \
                         вкусную пиццу в городе. Наша история началась давно, когда маленькая пиццерия  \
                         открыла свои двери в сердце города. Мы гордимся тем, что используем только  \
                         самые свежие и качественные ингредиенты. Наши повара тщательно отбирают продукты, \
                         чтобы каждая пицца, которая покидает нашу кухню, была наивкуснейшей и удовлетворяла \
                         самые изысканные вкусы. Наше меню разнообразно и удовлетворит даже самых взыскательных \
                         гурманов. Мы предлагаем классические варианты пиццы, а также авторские рецепты, \
                         которые не оставят вас равнодушными. Благодаря разнообразию начинок и теста вы  \
                         всегда найдете именно то, что угодит вашему вкусу. Наша цель — не просто приготовить  \
                         пиццу, а создать для вас незабываемый опыт. Мы с нетерпением ждем вас в нашей пиццерии!"
    }
    return render(request=request, template_name='main/about.html', context=context)

app_main/templates/main/about.html
{% extends "main/base.html" %}
{% load static %}

{% block modal_cart %}
{% include "baskets/includes/cart_button.html" %}
{% endblock modal_cart %}

{% block css %}
    <link rel="stylesheet" href="{% static "deps/css/my_footer_css.css" %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Nosifer&display=swap" rel="stylesheet">
{% endblock css %}


{% block content %}
<div class="mt-5 pt-5 custom-shadow d-flex justify-content-center align-items-center" style="height: 70vh;">
    <div class="text-center">
        <h2 class="font-nosifer mt-5"><strong>{{ content }}</strong></h2>
        <p class="font-nosifer">{{ text_on_page }}</p>
    </div>
</div>
{% endblock content %}

app_main/templates/main/base.html
{% load static %}
{% load prod_tag %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static "deps/css/bootstrap/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "deps/css/my_css.css" %}">
    {% block css %}
    {% endblock css %}
    <link rel="apple-touch-icon" sizes="180x180" href="{% static "deps/favicon/apple-touch-icon.png" %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static "deps/favicon/favicon-32x32.png" %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static "deps/favicon/favicon-16x16.png" %}">
    <link rel="manifest" href="{% static "deps/favicon/site.webmanifest" %}">
    <title>{{ title }}</title>
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
            <div class="container">
                <a class="navbar-brand" href="{% url "main:index" %}">Home</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item dropdown ">
                            <a class="nav-link dropdown-toggle text-white" href="#" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                Информация
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item  text-white" href="#">Доставка и оплата</a></li>
                                <li><a class="dropdown-item  text-white" href="#">Контактная информация</a></li>
                                <li><a class="dropdown-item  text-white" href="{% url "main:about" %}">Про нас</a></li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link  text-white" href="{% url "users:users_basket" %}">Корзина</a>
                        </li>

                        {% if not user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link  text-white" href="{% url "user:login" %}">Войти</a>
                            </li>
                        {% else %}
                            <li class="nav-item dropdown ">
                                <a class="nav-link dropdown-toggle text-white" href="#" role="button"
                                    data-bs-toggle="dropdown" aria-expanded="false">
                                    Мой профиль
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item  text-white" href="carts/cart.html">Корзина</a></li>
                                    <li><a class="dropdown-item  text-white" href="{% url "user:profile" %}">Личный кабинет</a>
                                    </li>
                                    {% if user.is_admin or user.is_staff %}
                                        <li><a class="dropdown-item  text-white" href="{% url "admin:index" %}">Админ панель</a></li>
                                    {% endif %}
                                    <li>
                                        <hr class="dropdown-divider">
                                    </li>
                                    <li><a class="dropdown-item  text-white" href="{% url "user:logout" %}">Выйти</a></li>
                                </ul>
                            </li>
                        {% endif %}
                    </ul>
                    <form class="d-flex" role="search" action="{% url "catalog:search" %}" method="get">
                        <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success text-white" type="submit">Поиск</button>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <section>
        <div class="container">
            <!-- Каталог и корзина с фиксированным расположением на странице -->
            <div class="row mt-1 position-fixed z-3">
                <!-- Каталог -->
                <div class="dropdown mb-2">
                    <button class="btn btn-secondary dropdown-toggle btn-dark" type="button" data-bs-toggle="dropdown"
                        aria-expanded="false">
                        Каталог
                        <img class="mx-1" src="{% static "deps/icons/grid-fill.svg" %}" alt="Catalog Icon" width="16"
                            height="16">
                    </button>
                    <ul class="dropdown-menu bg-dark" data-bs-theme="dark">
                        {% tag_categories as categories %}
                        {% for cat in categories %}
                            <li><a class="dropdown-item text-white" href="{% url "catalog:index" cat.slug %}">{{ cat.name }}</a></li> 
                        {% endfor %} 
                    </ul>
                </div>
                <!-- Значек корзины, вызывает модальное окно -->
                    {% block modal_cart %}in{% endblock modal_cart %}
                <!-- Закончилась разметка модального окна -->
            </div>
        </div>
        <!-- Контент -->
        <div class="container">
            <div class="row mt-1">
                <div class="col-lg-2">
                    <!-- Пустой блок на Ваше усмотрение -->
                </div>
                <div class="col-lg-10">
                    <!-- Контент на странице -->
                    {% include "main/notifications.html" %}
                    {% block content %}
                    {% endblock content %}
                </div>
            </div>
        </div>
    </section>
    {% block footer %}
    {% endblock footer %}
    <script src="{% static "deps/js/jquery/jquery-3.7.0.min.js" %}"></script>
    <script src="{% static "deps/js/jquery-ajax.js" %}"></script>
    <script src="{% static "deps/js/bootstrap/bootstrap.bundle.min.js" %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-element-bundle.min.js"></script>
</body>

</html>

app_main/templates/main/index.html
{% extends "main/base.html" %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static "deps/css/my_footer_css.css" %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Nosifer&display=swap" rel="stylesheet">
{% endblock css %}


{% block modal_cart %}
{% include "baskets/includes/cart_button.html" %}
{% endblock modal_cart %}

{% block content %}
    <h1 class="font-nosifer mt-5 pt-5"><strong>{{ content }}</strong></h1>
{% endblock content %}


{% block footer %}
<footer class="py-4 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; My Pizza House</p>
    </div>
</footer>
{% endblock footer %}

app_main/templates/main/notifications.html
{% load static %}

<div class="container mt-4">
    <div class="row justify-content-center">
        <div class="col-md-6">
            {% if messages %}
                {% for message in messages %}
                    {% if message.tags == 'success' %}
                    <div id="notification" class="position-fixed start-50 translate-middle-x z-3 alert alert-success fade show custom-shadow" role="alert">
                        {{ message }}
                    </div>
                    {% endif %}
                    {% if message.tags == 'warning' %}
                    <div id="notification" class="position-fixed start-50 translate-middle-x z-3 alert alert-danger fade show custom-shadow" role="alert">
                        {{ message }}
                    </div>
                    {% endif %}
                {% endfor %}
            {% else %}
            <div id="jq-notification" class="position-fixed start-50 translate-middle-x z-3 alert alert-success fade show custom-shadow" style="display: none;" role="alert">
            </div>
            {% endif %}
        </div>
    </div>
</div>