app_main/application/urls.py
from django.contrib import admin
from django.urls import include, path

from application import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace="main")),
    path('catalog/', include('products.urls', namespace="catalog")),
    path('user/', include('users.urls', namespace="user")),
    path('basket/', include('baskets.urls', namespace="basket")),
]

if settings.DEBUG:
    urlpatterns += [path("__debug__/", include("debug_toolbar.urls")),]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_main/baskets/urls.py
from django.urls import path
from baskets import views

app_name = "baskets"

urlpatterns = [
    path('basket_add/', view=views.basket_add, name='basket_add'),
    path('basket_change/', view=views.basket_change, name='basket_change'),
    path('basket_remove/', view=views.basket_remove, name='basket_remove'),
]

app_main/main/urls.py
from django.urls import path
from main import views

app_name = "main"

urlpatterns = [
    path('', view=views.index, name='index'),
    path('about/', view=views.about, name='about'),
]

app_main/products/urls.py
from django.urls import path
from products import views

app_name = "products"

urlpatterns = [
    path('search/', view=views.catalog, name='search'),
    path('<slug:category_slug>', view=views.catalog, name='index'),
    path('product/<slug:product_slug>/', view=views.product, name='product'),
]

app_main/products/models.py
from django.db import models
from django.urls import reverse


class Categories(models.Model):
    name = models.CharField(max_length=250, unique=True, verbose_name="Название")
    slug = models.SlugField(max_length=250, unique=True, null=True, blank=True, verbose_name="URL")
    display_number = models.IntegerField(default=0)

    class Meta:
        db_table = "category"
        verbose_name = "Категорию"
        verbose_name_plural = "Категории"
        ordering = ['display_number', 'name']

    def __str__(self):
        return self.name


class Products(models.Model):
    name = models.CharField(max_length=250, unique=True, verbose_name="Название")
    slug = models.SlugField(max_length=250, unique=True, null=True, blank=True, verbose_name="URL")
    description = models.TextField(blank=True, null=True, verbose_name="Описание")
    image = models.ImageField(upload_to="product_images", blank=True, null=True, verbose_name="Изображение")
    price = models.DecimalField(default=0.0, max_digits=5, decimal_places=1, verbose_name="Цена")
    discount = models.DecimalField(default=0, max_digits=3, decimal_places=1, verbose_name="Скидка (%)")

    category = models.ForeignKey(to=Categories, on_delete=models.SET_NULL, blank=True, null=True, verbose_name="Категория товара")

    class Meta:
        db_table = "product"
        verbose_name = "Продукт"
        verbose_name_plural = "Продукты"
        ordering = ['id']


    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("catalog:product", kwargs={"product_slug": self.slug})
    
    
    def display_id(self):
        return f"{self.id:05}"
    
    def sell_price(self):
        if self.discount:
            return round(self.price - (self.price*self.discount)/100, 2)

        return self.price

app_main/products/views.py
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, render

from products.models import Products, Categories
from products.utils import query_search


def catalog(request, category_slug=None):
    page = request.GET.get("page", 1)
    on_sale = request.GET.get("on_sale", None)
    order_by = request.GET.get("order_by", None)
    query = request.GET.get("q", None)

    if category_slug == "all":
        products = Products.objects.all()
    elif query:
        products = query_search(query)
    else:
        category = get_object_or_404(Categories, slug=category_slug)
        products = Products.objects.filter(category=category)

    if on_sale:
        products = products.filter(discount__gt=0)

    if order_by and order_by != "default":
        products = products.order_by(order_by)


    paginator = Paginator(object_list=products, per_page=3)
    current_page = paginator.page(int(page))

    context = {
        "title": "Catalog",
        "all_prod": current_page,
        "slug_url": category_slug
    }
    return render(request=request, template_name="products/catalog.html", context=context)



def product(request, product_slug):
    product = Products.objects.get(slug=product_slug)

    context = {
        "title": "Catalog",
        "product": product
    }
    return render(request=request, template_name="products/product.html", context=context)

app_main/templates/products/catalog.html
{% extends "main/base.html" %}
{% load static %}
{% load prod_tag %}

{% block modal_cart %}
{% include "baskets/includes/cart_button.html" %}
{% endblock modal_cart %}

{% block css %}
    <link rel="stylesheet" href="{% static "deps/css/my_footer_css.css" %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Nosifer&display=swap" rel="stylesheet">
{% endblock css %}


{% block content %}
<div class="row">
    <!-- Форма фильтров -->
    <div class="dropdown mb-2">
        <button class="btn btn-secondary dropdown-toggle btn-dark" type="button" data-bs-toggle="dropdown"
            aria-expanded="false">
            Фильтры
        </button>

        <form action="{% if request.GET.q %}{% url "catalog:search" %}{% else %}{% url "catalog:index" slug_url %}{% endif %}" method="get" class="dropdown-menu bg-dark" data-bs-theme="dark">
            <div class="form-check text-white mx-3">
                <input class="form-check-input" type="checkbox" name="on_sale" id="flexCheckDefault" value="on" {% if request.GET.on_sale == "on" %}checked{% endif %}>
                {% if request.GET.q %}
                    <input type="hidden" name="q" value="{{ request.GET.q }}">
                {% endif %}
                <label class="form-check-label" for="flexCheckDefault">
                    Товары по акции
                </label>
            </div>
            <p class="text-white mx-3 mt-3">Сортировать:</p>
            <div class="form-check text-white mx-3">
                <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault1" value="default" {% if not request.GET.order_by or request.GET.order_by == "default" %}checked{% endif %}>
                <label class="form-check-label" for="flexRadioDefault1">
                    По умолчанию
                </label>
            </div>
            <div class="form-check text-white mx-3">
                <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault2" value="price" {% if request.GET.order_by == "price" %}checked{% endif %}>
                <label class="form-check-label" for="flexRadioDefault2">
                    От дешевых к дорогим
                </label>
            </div>
            <div class="form-check text-white mx-3">
                <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault3" value="-price" {% if request.GET.order_by == "-price" %}checked{% endif %}>
                <label class="form-check-label" for="flexRadioDefault3">
                    От дорогих к дешевым
                </label>
            </div>
            <button type="submit" class="btn btn-primary mx-3 mt-3">Применить</button>
        </form>
    </div>


    {% if request.GET.q %}
    <h2 class="font-nosifer mt-5 pt-5">Результат поиска по запросу "{{ request.GET.q }}"</h2>
        {% if not all_prod %}
            <h1 class="font-nosifer mt-5 pt-5">По запросу ничего не найдено...</h1>
        {% endif %}
    {% endif %}

    {% for product in all_prod %}
        <!-- Карта товара -->
        <div class="col-lg-4 col-md-6 p-4">
            <div class="card border-primary rounded custom-shadow">
                {% if product.image %}
                    <img src="{{ product.image.url }}" class="card-img-top" alt="...">
                {% else %}
                    <img src="{% static "deps/images/Not found image.png" %}" class="card-img-top" alt="...">
                {% endif %}
                <div class="card-body">
                    <a href="{% url "catalog:product" product.slug %}">
                        <p class="card-title">{{ product.name }}</p>
                    </a>
                    <p class="card-text text-truncate">{{ product.description }}</p>
                    <p class="product_id">id: {{ product.display_id }}</p>
                    <div class="d-flex justify-content-between">
                        {% if product.discount %}
                            <p><s>{{ product.price }}</s> $</p>
                            <p><strong>{{ product.sell_price }} $</strong></p>
                            <span class="badge bg-warning text-dark">Скидка {{ product.discount }} %</span>
                        {% else %}
                            <p><strong>{{ product.price }}</strong></p>
                        {% endif %}
                        <a href="{% url 'baskets:basket_add' %}" class="btn add-to-cart" data-product-id="{{ product.id }}">
                            {% csrf_token %}
                            <img class="mx-1" src="{% static 'deps/icons/cart-plus.svg' %}" alt="Catalog Icon" width="32" height="32">
                        </a>                        
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}


</div>
<!-- Пагинация -->
{% if all_prod %}
<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center my-4">
        <div class="custom-shadow d-flex">
            <li class="page-item {% if not all_prod.has_previous %}disabled{% endif %}">
              <a class="page-link" href="{% if all_prod.has_previous %}?{% change_params page=all_prod.previous_page_number %}{% else %}#{% endif %}">Назад</a>
            </li>
            
            {% for page in all_prod.paginator.page_range %}
                {% if page >= all_prod.number|add:-2 and page <= all_prod.number|add:2 %}
                    <li class="page-item {% if all_prod.number == page %}disabled{% endif %}">
                        <a class="page-link" href="?{% change_params page=page %}">{{ page }}</a>
                    </li>
                {% endif %}
            {% endfor %}

            <li class="page-item {% if not all_prod.has_next %}disabled{% endif %}">
                <a class="page-link" href="{% if all_prod.has_next %}?{% change_params page=all_prod.next_page_number %}{% else %}#{% endif %}">Следующая</a>
            </li>
        </div>
    </ul>
</nav>
{% else %}
{% endif %}

{% endblock content %}

app_main/templates/products/product.html
{% extends "main/base.html" %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static "deps/css/my_footer_css.css" %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Nosifer&display=swap" rel="stylesheet">
{% endblock css %}


{% block modal_cart %}
{% include "baskets/includes/cart_button.html" %}
{% endblock modal_cart %}

{% block content %}
<div class="container mt-5">
    <div class="card mb-4 custom-shadow">
        <div class="row">
            <!-- Миниатюры -->
            <div class="col-md-4">
                <img src="{{ product.image.url }}"
                    class="img-thumbnail" data-bs-toggle="modal" data-bs-target="#imageModal1">
            </div>
            <div class="col-md-4 ">
                <p class="product_id mt-3">id: {{ product.display_id }}</p>
            </div>
            <!-- Увеличить изображение в модальном окне -->
            <div class="modal fade" id="imageModal1" tabindex="-1"
                aria-labelledby="imageModal1Label" aria-hidden="true">
                <div class="modal-dialog modal-lg">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="imageModal1Label">{{ product.name }}</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal"
                                aria-label="Закрыть"></button>
                        </div>
                        <div class="modal-body">
                            <img src="{{ product.image.url }}"
                                class="img-fluid" alt="Изображение 1">
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Описание товара -->
        <div class="card-body">
            <p class="card-text">Цена: <strong>{{ product.sell_price }} $</strong></p>
            <h5 class="card-title">{{ product.name }}</h5>
            <p class="card-text">{{ product.description }}</p>
            <a href="{% url "baskets:basket_add" %}" class="btn btn-dark add-to-cart" data-product-id="{{ product.id }}">
                {% csrf_token %}
                Добавить в корзину
            </a>
        </div>
    </div>
</div>
{% endblock content %}

{% block footer %}
<footer class="py-4 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; My Pizza House</p>
    </div>
</footer>
{% endblock footer %}