app_main/application/urls.py
from django.contrib import admin
from django.urls import include, path

from application import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace="main")),
    path('catalog/', include('products.urls', namespace="catalog")),
    path('user/', include('users.urls', namespace="user")),
    path('basket/', include('baskets.urls', namespace="basket")),
]

if settings.DEBUG:
    urlpatterns += [path("__debug__/", include("debug_toolbar.urls")),]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_main/baskets/urls.py
from django.urls import path
from baskets import views

app_name = "baskets"

urlpatterns = [
    path('basket_add/', view=views.basket_add, name='basket_add'),
    path('basket_change/', view=views.basket_change, name='basket_change'),
    path('basket_remove/', view=views.basket_remove, name='basket_remove'),
]

app_main/main/urls.py
from django.urls import path
from main import views

app_name = "main"

urlpatterns = [
    path('', view=views.index, name='index'),
    path('about/', view=views.about, name='about'),
]

app_main/baskets/models.py
from django.db import models

from products.models import Products
from users.models import User


class BasketQuerySet(models.QuerySet):
    
    def total_price_all_users_baskets(self):
        return sum([cart.products_price() for cart in self])

    def total_quantity(self):
        if self:
            return sum([cart.quantity for cart in self])
        return 0


class Basket(models.Model):

    user = models.ForeignKey(to=User, on_delete=models.CASCADE, verbose_name="Пользователь", blank=True, null=True)
    product = models.ForeignKey(to=Products, on_delete=models.CASCADE, verbose_name="Товар")
    quantity = models.PositiveSmallIntegerField(default=0, verbose_name="Количество")
    session_key = models.CharField(max_length=32, blank=True, null=True)
    created_on = models.DateTimeField(auto_now_add=True, verbose_name="Дата/Время добавления")

    class Meta:
        db_table = "baskets"
        verbose_name = "Корзину"
        verbose_name_plural = "Корзины"
        ordering = ['created_on']

    objects = BasketQuerySet().as_manager()

    def products_price(self):
        return round(self.product.sell_price() * self.quantity, 2)

    def __str__(self):
        return f"Корзина {self.user.username} / Товар {self.product.name}"

app_main/baskets/views.py
from django.http import JsonResponse
from django.shortcuts import redirect
from django.template.loader import render_to_string
from baskets.models import Basket
from baskets.utils import get_user_baskets
from products.models import Products
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist


def basket_add(request):
    try:
        product_id = request.POST.get("product_id")
        product = Products.objects.get(id=product_id)

        if request.user.is_authenticated:
            carts = Basket.objects.filter(user=request.user, product=product)
            if carts.exists():
                carts = carts.first()
                if carts:
                    carts.quantity += 1
                    carts.save()
            else:
                Basket.objects.create(user=request.user, product=product, quantity=1)

        else:
            carts = Basket.objects.filter(session_key=request.session.session_key, product=product)

            if carts.exists():
                cart = carts.first()
                if cart:
                    cart.quantity += 1
                    cart.save()
            else:
                Basket.objects.create(session_key=request.session.session_key, product=product, quantity=1)


        user_cart = get_user_baskets(request)
        cart_items_html = render_to_string(
            "baskets/includes/included_basket.html", {"carts": user_cart}, request=request)

        response_data = {
            "message": "Товар добавлен в корзину",
            "cart_items_html": cart_items_html,
        }

        return JsonResponse(response_data)

    except ObjectDoesNotExist:
        messages.warning(request=request, message=f"{request.user.username}, товар не найден!!!")
        return redirect(request.META["HTTP_REFERER"])




def basket_change(request):
    try:
        cart_id = request.POST.get("cart_id")
        quantity = request.POST.get("quantity")

        cart = Basket.objects.get(id=cart_id)

        cart.quantity = quantity
        cart.save()
        updated_quantity = cart.quantity

        cart = get_user_baskets(request)
        cart_items_html = render_to_string(
            "baskets/includes/included_basket.html", {"carts": cart}, request=request)

        response_data = {
            "message": "Количество изменено",
            "cart_items_html": cart_items_html,
            "quaantity": updated_quantity,
        }

        return JsonResponse(response_data)
    
    except ObjectDoesNotExist:
        messages.warning(request=request, message=f"{request.user.username}, товар не найден!!!")
        return redirect(request.META["HTTP_REFERER"])




def basket_remove(request):
    try:
        cart_id = request.POST.get("cart_id")
        cart = Basket.objects.get(id=cart_id)
        quanity = cart.quantity
        cart.delete()

        user_cart = get_user_baskets(request)
        cart_items_html = render_to_string(
        "baskets/includes/included_basket.html", {"carts": user_cart}, request=request)

        response_data = {
            "message": "Товар удален из корзины",
            "cart_items_html": cart_items_html,
            "quantity_deleted": quanity
        }

        return JsonResponse(response_data)
    
    except ObjectDoesNotExist:
        messages.warning(request=request, message=f"{request.user.username}, товар не найден!!!")
        return redirect(request.META["HTTP_REFERER"])

app_main/templates/baskets/includes/cart_button.html
{% load static %}
{% load baskets_tags %}

{% user_carts request as carts %}

<div>
    <button type="button" class="btn btn-dark btn-secondary d-flex" id="modalButton"
        aria-expanded="false">
        <img class="mx-1" src="{% static "deps/icons/basket2-fill.svg" %}" alt="Catalog Icon" width="24"
            height="24">
        <span id="goods-in-cart-count">{{ carts.total_quantity }}</span>
    </button>
</div>
<!-- Разметка модального окна корзины -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog modal-dialog-scrollable">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="btn-close" data-bs-dismiss="modal"
                    aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <h3 class="text-center mb-4">Корзина</h3>
                <div class="container" id="cart-items-container">
                    <!-- Разметка корзины -->
                    {% include "baskets/includes/included_basket.html" %}
                    <!-- Закончилась разметка корзины -->
                </div>
                {% if carts %}
                <a class="btn btn-dark" href="orders/create_order.html">
                    Оформить заказ
                </a>
                {% endif %}
            </div>
        </div>
    </div>
</div>

app_main/templates/baskets/includes/included_basket.html
{% load static %}


<div class="card mb-3 text-bg-light shadow-lg">
    {% for cart in carts %}
    <div class="card-header">
        <h5 class="card-title">{{ cart.product.name }}</h5>
    </div>
    <ul class="list-group list-group-flush">
        <li class="list-group-item">
            <div class="row text-center">
                <div class="col p-0">
                    <div class="input-group">
                        <span class="input-group-btn">
                            <button type="button" class="btn btn-dark btn-sm decrement"
                                data-cart-id="{{ cart.id }}" data-cart-change-url="{% url "basket:basket_change" %}">{% csrf_token %}-</button>
                        </span>
                        <input type="text" class="form-control number" value="{{ cart.quantity }}" readonly>
                        <span class="input-group-btn">
                            <button type="button" class="btn btn-dark btn-sm increment"
                                data-cart-id="{{ cart.id }}" data-cart-change-url="{% url "basket:basket_change" %}">{% csrf_token %}+</button>
                        </span>
                    </div>
                </div>
                <div class="col p-0">
                    <p>x {{ cart.product.sell_price }} = </p>
                </div>
                <div class="col p-0"><strong>{{ cart.products_price }} $</strong></div>
                <div class="col p-0">
                    <a href="{% url "baskets:basket_remove" %}" class="remove-from-cart" data-cart-id="{{ cart.id }}">
                        {% csrf_token %}
                        <img class="mx-1" src="{% static "deps/icons/trash3-fill.svg" %}"
                            alt="Catalog Icon" width="16" height="16">
                    </a>
                </div>
            </div>
        </li>
    </ul>
    {% endfor %}
</div>
<div class="card mb-3 shadow-lg">
    <div class="card-footer">
        <p class="float-left">Итого <strong>{{ carts.total_quantity }}</strong> товар(а) на сумму</p>
        <h4 class="float-left"><strong>{{ carts.total_price_all_users_baskets }} $</strong></h4>
    </div>
</div>